# Generated by Django 2.1.7 on 2019-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Image', models.ImageField(default='', upload_to='image/')),
                ('Subtitle', models.CharField(default='', max_length=5)),
                ('Director', models.CharField(default='', max_length=20)),
                ('Genre', models.CharField(default='', max_length=50)),
                ('Review', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
