# Generated by Django 2.1.7 on 2019-03-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood'), ('Pollywood', 'Pollywood'), ('Tollywood', 'Tollywood')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('Subtitle', models.CharField(default='', max_length=5)),
                ('Director', models.CharField(default='', max_length=20)),
                ('Genre', models.CharField(default='', max_length=50)),
                ('Review', models.TextField(default='', max_length=200)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
