# Generated by Django 2.1.7 on 2019-03-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20190318_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
