# Generated by Django 2.1.7 on 2019-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190318_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Director',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Subtitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
