# Generated by Django 2.1.7 on 2019-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190317_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood'), ('Pollywood', 'Pollywood'), ('Tollywood', 'Tollywood')], max_length=30),
        ),
    ]
