# Generated by Django 2.1.7 on 2019-03-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190317_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
            preserve_default=False,
        ),
    ]
